services:
  quiz-engine:
    container_name: quiz-engine
    build: .
    restart: unless-stopped

    env_file:
      - .env

    networks:
      - proxy
      - backend

    labels:
      - traefik.enable=true

      # Router
      - traefik.http.routers.quiz-engine.rule=Host(`quiz-engine.localhost`)
      - traefik.http.routers.quiz-engine.entrypoints=websecure
      - traefik.http.routers.quiz-engine.tls=true

      # Service
      - traefik.http.services.quiz-engine.loadbalancer.server.port=8000

networks:
  proxy:
    external: true
  backend:
    external: true
